name: royas

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "roya bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script for royatv
        run: python3 platforms/royatv.py
        
      - name: Execute Python script for royasport
        run: python3 platforms/royasport.py

      - name: Execute Python script for royanews
        run: python3 platforms/royanews.py      

      - name: git add
        run: |
          git add -A
          ls -la 

      - name: commit & push
        run: |
          git pull origin main
          git commit -m "royas updated $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
